.base: &base
  # Test on debian stable
  image: "rust:slim-trixie"
  variables:
    # Set CARGO_HOME inside the CI directory, otherwise cargo won't use the cache.
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  before_script:
    - apt-get -y update
    - apt-get -y install libclang-19-dev llvm-19-dev

lint:clippy:
  <<: *base
  script:
    - rustup component add clippy
    - cargo clippy

test:alpine:
  <<: *base
  image: "rust:alpine"
  # clang-libs are needed by bindgen. build-base contains various needed things,
  # among which crti.o and pkg-config.
  variables:
    # Let rust create dynamically linked builds under musl libc - see [this rust
    # issue](https://github.com/rust-lang/compiler-team/issues/422)
    RUSTFLAGS: "-C target-feature=-crt-static"     
    # Same consideration for doc tests - see [this rust
    # issue](https://github.com/rust-lang/cargo/issues/6650)
    RUSTDOCFLAGS: "-C target-feature=-crt-static"  
  before_script:
    - apk update
    - apk add build-base clang-dev llvm-dev
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose --release

test:debian-stable:
  <<: *base
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose --release
